// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDiscounts():Promise<string>;

export function GetAllMenu():Promise<string>;

export function SendBasket():Promise<string>;
