// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllBasket() {
  return window['go']['main']['App']['GetAllBasket']();
}

export function GetAllDiscounts() {
  return window['go']['main']['App']['GetAllDiscounts']();
}

export function GetAllMenu() {
  return window['go']['main']['App']['GetAllMenu']();
}

export function SendAllBasket(arg1) {
  return window['go']['main']['App']['SendAllBasket'](arg1);
}
